// File generated by FlutterFire CLI.
// This file contains Firebase configuration options for your Flutter application.
// You should replace these placeholder values with your actual Firebase configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk-Zer1LUCud3ZOY59DYOrZNX7KFgGgTk',
    appId: '1:474299308134:web:fb4c71f111156a392375a7',
    messagingSenderId: '474299308134',
    projectId: 'tomofude-dev',
    authDomain: 'tomofude-dev.firebaseapp.com',
    storageBucket: 'tomofude-dev.firebasestorage.app',
    measurementId: 'G-FJ51BP3GP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-rYEkF2ELGO0IajRBI5zyBdptxJ-Bup4',
    appId: '1:474299308134:android:3afd083292a660b32375a7',
    messagingSenderId: '474299308134',
    projectId: 'tomofude-dev',
    storageBucket: 'tomofude-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgMPDBaYXdlUBDIWTuVU-oI3xa8US1uxc',
    appId: '1:474299308134:ios:d35a044dc60da1942375a7',
    messagingSenderId: '474299308134',
    projectId: 'tomofude-dev',
    storageBucket: 'tomofude-dev.firebasestorage.app',
    iosClientId: '474299308134-mmb5jt7achqt2cfh4eru143g9gookn5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.tomofude',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgMPDBaYXdlUBDIWTuVU-oI3xa8US1uxc',
    appId: '1:474299308134:ios:d35a044dc60da1942375a7',
    messagingSenderId: '474299308134',
    projectId: 'tomofude-dev',
    storageBucket: 'tomofude-dev.firebasestorage.app',
    iosClientId: '474299308134-mmb5jt7achqt2cfh4eru143g9gookn5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.tomofude',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk-Zer1LUCud3ZOY59DYOrZNX7KFgGgTk',
    appId: '1:474299308134:web:0b16bc4c57024f292375a7',
    messagingSenderId: '474299308134',
    projectId: 'tomofude-dev',
    authDomain: 'tomofude-dev.firebaseapp.com',
    storageBucket: 'tomofude-dev.firebasestorage.app',
    measurementId: 'G-HZ6QRHN6EB',
  );

}